name: 'Terraform Apply'

on:
  workflow_dispatch:

permissions: write-all

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_REGION: "eu-west-3"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Ensure Terraform Directory Exists
      run: mkdir -p terraform

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3

    - name: Validate AWS Credentials
      run: aws sts get-caller-identity

    - name: Set AWS Account ID
      id: account
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

    - name: Create S3 Bucket for Terraform State
      run: |
        BUCKET_NAME="bedrock-state-files-${{ env.ACCOUNT_ID }}"
        if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
          echo "Creating S3 bucket: $BUCKET_NAME"
          aws s3api create-bucket --bucket "$BUCKET_NAME" --region $AWS_REGION
        else
          echo "S3 bucket already exists: $BUCKET_NAME"
        fi

    - name: Check for Existing Terraform State
      id: check_state
      run: |
        if aws s3api head-object --bucket bedrock-state-files-${{ env.ACCOUNT_ID }} --key terraform.tfstate 2>/dev/null; then
          echo "STATE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "STATE_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0  

    - name: Retrieve Terraform State (if exists)
      run: |
        if [[ "$STATE_EXISTS" == "true" ]]; then
          aws s3 cp s3://bedrock-state-files-${{ env.ACCOUNT_ID }}/terraform.tfstate ./terraform/terraform.tfstate || true
        fi

    - name: Terraform Init & Apply
      run: |
        cd terraform
        terraform init
        terraform plan -input=false
        terraform apply -auto-approve -input=false

    - name: Ensure Terraform State Exists
      run: |
        if [ ! -f "./terraform/terraform.tfstate" ]; then
          echo "Error: Terraform state file missing!"
          exit 1
        fi

    - name: Upload Terraform State to S3
      if: always()
      run: |
        aws s3 cp ./terraform/terraform.tfstate s3://bedrock-state-files-${{ env.ACCOUNT_ID }}/terraform.tfstate
