name: 'Terraform Destroy'

on:
  workflow_dispatch:

permissions: write-all

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_REGION: "eu-west-3"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Ensure Terraform Directory Exists
      run: mkdir -p terraform

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
